name: run-deno-tests
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - ready_for_review
            - locked
            - unlocked
    push:
        branches:
            - master
jobs:
    check-generated-parser:
        runs-on: ubuntu-latest
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.16"
            - uses: actions/checkout@master
              with:
                  repository: python/cpython
                  ref: "v3.9.16"
                  path: cpython
            - uses: actions/checkout@master
              with:
                  path: skulpt_parser
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - run: pip install --user pre-commit
            - name: build parser
              run: deno task gen-parser
              working-directory: "./skulpt_parser"
            - name: assert clean repo
              run: git diff-index --quiet --cached HEAD --
              working-directory: "./skulpt_parser"
    run-tests:
        runs-on: ubuntu-latest
        outputs:
            tests: ${{ steps.run-tests.outputs.test }}
        steps:
            - uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9.16"
            - uses: actions/checkout@master
            - run: echo "$HOME/.deno/bin" >> $GITHUB_PATH
            - name: run tests
              run: deno test -A --unstable
